# Generated by Django 4.1.10 on 2023-11-10 21:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verify_token",
            field=models.CharField(
                default=accounts.models.generate_security_token, max_length=250
            ),
        ),
    ]
