# Generated by Django 4.1.2 on 2022-11-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsvalue',
            name='options',
        ),
        migrations.AddField(
            model_name='optionsvalue',
            name='option',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='store.options'),
            preserve_default=False,
        ),
    ]
