# Generated by Django 4.1.2 on 2022-11-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_optionsvalue_options_optionsvalue_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionsvalues', to='store.options'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product'),
        ),
    ]
