# Generated by Django 4.1.2 on 2022-11-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_optionsvalue_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productvariants', to='store.options'),
            preserve_default=False,
        ),
    ]
