# Generated by Django 4.1.2 on 2022-12-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_productvariant_variant_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_favorites',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='OptionsValue',
            new_name='Value',
        ),
        migrations.AlterField(
            model_name='value',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values',
                                    to='store.option'),
        ),
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='ProductOptionValue',
        ),
        migrations.RenameField(
            model_name='productoptionvalue',
            old_name='variant',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_values',
                                    to='store.value'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_options',
                                    to='store.option'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_values',
                                    to='store.product'),
        ),
    ]
